/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  97: {
    TokenFactory: {
      address: "0x94737C7b4EE0860e7142988590d23eFAC32072Ef",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_dexRouter",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "tokenAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "saleAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "vaultAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "oracleAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "bootstrapperAddress",
              type: "address",
            },
          ],
          name: "TokenLaunched",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "symbol",
              type: "string",
            },
          ],
          name: "createTokenLaunch",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "dexRouter",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 92938896,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
